version: '3.9'

services:
  app:
    container_name: pasha_nestjs
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    command: sh -c "npm run start:dev"
    env_file:
      - .env
    network_mode: host
    depends_on:
      - postgres
  postgres:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=my_postgres_db_pasha
      - POSTGRES_USER=pasha_kuraksin
      - POSTGRES_PASSWORD=postgre_pasha_password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
